### ISSUE TITLE
Back buttons

### ISSUE THREAD

**Issue by flamespinner** [mparobotics/MPAror-Scouting-App-2015#1]
After going into a "menu" there is no back button in the upper right had corner to bring the menu back up. the swipe gesture does work however.

**Comment by bcbee** [comment]
For now, that is just a design flaw. Swiping left or rotating to landscape isn't too bad. If I have time to fix it I will. Labeling nofix.

**Comment by bcbee** [comment]
Orientation will be locked to landscape. This issue is irrelevant after this change.
