### ISSUE TITLE
Interface Builder error

### ISSUE THREAD

**Issue by flamespinner** [mparobotics/MPAror-Scouting-App-2015#3]
"interface builder storyboard: Line 1088: StartTag: Invalid Element Name"

**Comment by bcbee** [comment]
Please describe the action that triggers this crash

**Comment by flamespinner** [comment]
Just trying to build it in xcode. Building it for Simulator (ipad2). (Clicked run button, build failed, gave me the error)

**Comment by bcbee** [comment]
Are you on the latest version of Xcode, building for iOS 8.1?

**Comment by flamespinner** [comment]
Had to change the team to "none"
